/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bot {
  'id' : bigint,
  'status' : string,
  'activityLevel' : string,
  'username' : string,
  'movementStyle' : string,
  'behaviors' : Array<string>,
  'owner' : Principal,
  'mcVersion' : string,
  'name' : string,
  'createdAt' : bigint,
  'serverHost' : string,
  'serverPort' : bigint,
  'notes' : [] | [string],
  'chatPersonality' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBot' : ActorMethod<
    [
      string,
      string,
      Array<string>,
      string,
      string,
      string,
      string,
      bigint,
      string,
      [] | [string],
    ],
    bigint
  >,
  'deleteBot' : ActorMethod<[bigint], undefined>,
  'getBot' : ActorMethod<[bigint], Bot>,
  'getBots' : ActorMethod<[], Array<Bot>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStatus' : ActorMethod<[bigint, string], undefined>,
  'updateBot' : ActorMethod<
    [
      bigint,
      string,
      string,
      Array<string>,
      string,
      string,
      string,
      string,
      bigint,
      string,
      [] | [string],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];